"""
Implements a basic evolutionary cycle for a Genetic Algorithm (AG) to optimize
routes in a TSP/VRP-like context, comparing with the random initial population.

Author: Fábio Gandini
Date: June 2025
"""

# Native Modules:
import copy
import random

# Local Modules:
import routing
from utils import generate_seeds

# External Modules:
import numpy as np
from scipy.spatial.distance import cdist


def _order_crossover(parent1:list[int], parent2:list[int]) -> list[int]:
    """
    Private local function: Applies Order Crossover (OX) to generate a child route from two parents.

    Parameters:
        - `parent1: list[int]` -> The first parent route (a permutation of point indices).
        - `parent2: list[int]` -> The second parent route.

    Returns:
        - A new child route generated by preserving a subsequence from the first parent and filling
    the rest with the order of genes from the second.

    Notes:
        - The crossover preserves the relative order and position of a subset from parent1, while
    ensuring all genes are present with no duplication.
    """

    size:int = len(parent1)
    child:list[int] = [None] * size

    start, end = sorted(random.sample(range(size), 2))
    child[start:end+1] = parent1[start:end+1]

    fill:list[int] = [gene for gene in parent2 if gene not in child]

    fill_idx = 0
    for i in range(size):
        if child[i] is None:
            child[i] = fill[fill_idx]
            fill_idx += 1

    return child


def _swap_mutation(route:list[int], mutation_rate:float) -> list[int]:
    """
    Applies swap mutation to a route by randomly swapping two genes
    with a given mutation probability.

    Parameters:
        - `route: list[int]`        -> A route represented by a list of point indices.
        - `mutation_rate: float`    -> Probability (0 to 1) that each gene will be involved in a swap.

    Returns:
        - A new route where some elements may be swapped, depending on mutation rate.
    """

    route:list[int] = copy.deepcopy(route)

    for i in range(len(route)):
        if random.random() < mutation_rate:
            j = random.randint(0, len(route) - 1)
            route[i], route[j] = route[j], route[i]
    
    return route


def run_evolutionary_experiment(config:dict, points:np.ndarray, seed:int, crossover_rate:float=0.8, mutation_rate:float=0.1) -> dict:
    """
    Executes a full genetic algorithm cycle to evolve a population of routes and return the best one
    found after a number of generations.

    Parameters:
        - `config: dict`            -> Loaded config dictionary.
        - `points: numpy.ndarray`   -> 2D coordinates of the points used.
        - `seed: int`               -> Seed for reproducibility.
        - `crossover_rate: float`   -> Optional: Probability of applying crossover between pairs, default is 0.8.
        - `mutation_rate: float`    -> Optional: Probability of mutation per gene, default is 0.1.

    Returns:
        - A dictonary type with the following keys: \n
            `'route': list[int]`        -> The best route found (lowest distance).
            `'distance': float`         -> Total distance of the best route.
            `'points': numpy.ndarray`   -> 2D coordinates of the points used.
            `'history': list[float]`    -> Best distance at each generation.

    Notes:
        - The algorithm uses tournament selection (size 2), Order Crossover (OX), and swap mutation
        to evolve the population.
        - Only the best individual from the final generation is returned.
    """

    # Seeds the plot point generation and population:
    if seed is None:
        seed = generate_seeds(1)[0]
    random.seed(seed)
    np.random.seed(seed)

    distance_matrix = cdist(points, points)                                                     # Compute paiwise distances.
    population = routing.gen_initial_pop(config['Population_Size'], config['Number_of_Points']) # Generate initial population.
    evaluation_scores = [routing.evaluate_route(r, distance_matrix) for r in population]        # Evaluate each route.
    history = [min(evaluation_scores)]                                                          # Initializes convergence tracking by storing the smallest distance from the initial population.

    for _ in range(config['Number_of_Generations']):
        # Selection (tournament size 2)
        selected = [min(random.sample(population, 2), key=lambda r: routing.evaluate_route(r, distance_matrix)) for _ in range(config['Population_Size'])]

        # Crossover
        offspring = []
        for i in range(0, config['Population_Size'], 2):
            p1, p2 = selected[i], selected[(i + 1) % config['Population_Size']]
            if random.random() < crossover_rate:
                c1 = _order_crossover(p1, p2)
                c2 = _order_crossover(p2, p1)
            else:
                c1, c2 = copy.deepcopy(p1), copy.deepcopy(p2)
            offspring.extend([c1, c2])

        # Mutation
        mutated = [_swap_mutation(child, mutation_rate) for child in offspring]

        # Evaluation and replacement
        population = mutated
        evaluation_scores = [routing.evaluate_route(r, distance_matrix) for r in population]
        history.append(min(evaluation_scores))

    best_idx:np.intp = np.argmin(evaluation_scores)
    return {
        "route": population[best_idx],
        "distance": evaluation_scores[best_idx],
        "points": points,
        "history": history,
    }


# This is NOT a script file.
if __name__ == '__main__':
    raise RuntimeError("This module is not a standalone script.")
